name: js-reactjs-learning

services:
    react:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: Laravel-React-Frontend
        ports:
            - 3002:3000
        volumes:
            - ./:/app
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                reservations:
                    cpus: '0.5'
                    memory: 256M
